name: godot-ci export
on: push

env:
  GODOT_VERSION: 4.5.1
  PROJECT_PATH: game

jobs:
  export-web:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -p public/game
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../public/game/index.html

      - name: Deploy to Netlify Branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git switch -C netlify
          rm -rf ./*
          cp -r ../public/* .
          git add -A
          git commit -m "Deploy" || true
          git push origin netlify --force
