name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.5.1
  PROJECT_PATH: game

permissions:
  contents: write

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -p public/game
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../public/game/index.html

      - name: Push to surge branch
        run: |
          # https://github.com/actions/checkout/issues/363
          git config --global --add safe.directory "$PWD"

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --single-branch --branch surge https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git surge-deploy
          cd surge-deploy
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name 'index.html' ! -name 'styles.css' -exec rm -rf {} +
          cp -r ../public/* .
          git add .
          git commit -m "Deploy build from ${{ github.sha }}" || echo "No changes to commit"
          git push origin surge

      - name: Install and Deploy to Surge
        run: |
          apt-get install -y nodejs npm
          
          npm install -g surge
          surge ./surge-deploy ddu-kemispillet.surge.sh --token ${{ secrets.SURGE_TOKEN }}
